spring.application.name=base
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/base-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:base}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:base123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=${LOG_HIBERNATE_SQL:INFO}
logging.level.org.hibernate.type.descriptor.sql=${LOG_HIBERNATE_TYPES:INFO}
